app/Models/VehicleModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class VehicleModel extends Model
{
    use HasFactory;
    protected $table = 'vehicle_model';
    public $timestamps = false;
    public function brand(){
        return $this->belongsTo(Brand::class,'id','brand_id');
    }
}

app/Http/Controllers/Master/VehicleModelController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use App\Models\VehicleModel;
use App\Models\Brand;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Validator;


class VehicleModelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keywords = $request->keywords;
            $collection = VehicleModel::where('name','like','%'.$keywords.'%')
            ->paginate(10);
            return view('page.office.vehicleModel.list', compact('collection'));
        }
        return view('page.office.vehicleModel.main');
    }
    public function create()
    {
        $brand = Brand::get();
        return view('page.office.vehicleModel.input', ['vehicleModel' => new VehicleModel,'brand'=>$brand]);
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'brand_id' => 'required',
        ]);

        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name'),
                ]);
            }else{
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('brand_id'),
                ]);
            }
        }
        $vehicleModel = new VehicleModel;
        $vehicleModel->name = Str::title($request->name);
        $vehicleModel->slug = Str::slug($request->name);
        $vehicleModel->brand_id = $request->brand_id; 
        $vehicleModel->save();
        return response()->json([
            'alert' => 'success',
            'message' => 'VehicleModel '. $request->name . ' tersimpan',
        ]);
    }
    public function show(VehicleModel $vehicleModel)
    {
        //
    }
    public function edit(VehicleModel $vehicleModel)
    {
        $brand = Brand::get();
        return view('page.office.vehicleModel.input', ['vehicleModel' => $vehicleModel,'brand'=>$brand]);
    }
    public function update(Request $request, VehicleModel $vehicleModel)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'brand_id' => 'required',
        ]);

        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name'),
                ]);
            }else{
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('brand_id'),
                ]);
            }
        }
        $vehicleModel->name = Str::title($request->name);
        $vehicleModel->slug = Str::slug($request->name); 
        $vehicleModel->brand_id = $request->brand_id; 
        $vehicleModel->update();
        return response()->json([
            'alert' => 'success',
            'message' => 'VehicleModel '. $request->name . ' tersimpan',
        ]);
    }
    public function destroy(VehicleModel $vehicleModel)
    {
        $vehicleModel->delete();
        return response()->json([
            'alert' => 'success',
            'message' => 'VehicleModel '. $vehicleModel->name . ' terhapus',
        ]);
    }
}

app/Http/Controllers/Office/AuthController.php
<?php

namespace App\Http\Controllers\Office;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Employee;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class AuthController extends Controller
{
    public function __construct()
    {
        $this->middleware('guest:office')->except('do_logout');
    }
    public function index()
    {
        return view('page.office.auth.main');
    }
    public function do_login(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required|email|max:255',
            'password' => 'required|min:8',
        ]);

        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('email')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('email'),
                ]);
            }else{
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('password'),
                ]);
            }
        }
        if(Auth::guard('office')->attempt(['email' => $request->email, 'password' => $request->password], $request->remember))
        {
            return response()->json([
                'alert' => 'success',
                'message' => 'Welcome back '. Auth::guard('office')->user()->name,
                'redirect' => 'dashboard',
            ]);
        }else{
            return response()->json([
                'alert' => 'error',
                'message' => 'Sorry, looks like there are some errors detected, please try again.',
            ]);
        }
    }
    public function do_logout()
    {
        $employee = Auth::guard('office')->user();
        Auth::logout($employee);
        return redirect()->route('office.auth.index');
    }
}

app/Http/Controllers/Office/BannerController.php
<?php

namespace App\Http\Controllers\Office;

use App\Http\Controllers\Controller;
use App\Models\Banner;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Validator;

class BannerController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keywords = $request->keywords;
            $collection = Banner::where('title','like','%'.$keywords.'%')
            ->paginate(10);
            return view('page.office.banner.list', compact('collection'));
        }
        return view('page.office.banner.main');
    }
    public function create()
    {
        return view('page.office.banner.input', ['banner' => new Banner]);
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'desc' => 'required',
            'url' => 'required',
            'photo' => 'required',
        ]);

        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('title')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('title'),
                ]);
            }
        }
        elseif ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('desc')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('desc'),
                ]);
            }
        }
        elseif ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('url')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('url'),
                ]);
            }
        }
        elseif ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('photo')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('photo'),
                ]);
            }
        }
        $data = new Banner;
        if(request()->file('photo')){
            $photo = request()->file('photo')->store("banner");
            $data->photo = $photo;
        }
        $data->title = Str::title($request->title);
        $data->desc = $request->desc;
        $data->url = $request->url;
        $data->save();
        return response()->json([
            'alert' => 'success',
            'message' => 'Banner '. $request->title . ' tersimpan',
        ]);
    }
    public function show(Banner $banner)
    {
        //
    }
    public function edit(Banner $banner)
    {
        return view('page.office.banner.input', compact('banner'));
    }
    public function update(Request $request, Banner $banner)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'desc' => 'required',
            'url' => 'required',
            'photo' => 'required',
        ]);

        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('title')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('title'),
                ]);
            }
        }
        elseif ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('desc')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('desc'),
                ]);
            }
        }
        elseif ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('url')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('url'),
                ]);
            }
        }
        elseif ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('photo')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('photo'),
                ]);
            }
        }
        if(request()->file('photo')){
            Storage::delete($banner->company_logo);
            $photo = request()->file('photo')->store("banner");
            $banner->photo = $photo;
        }
        $banner->title = Str::title($request->title);
        $banner->desc = $request->desc;
        $banner->url = $request->url;
        $banner->update();
        return response()->json([
            'alert' => 'success',
            'message' => 'Banner '. $request->title . ' terupdate',
        ]);
    }
    public function destroy(Banner $banner)
    {
        Storage::delete($banner->photo);
        $banner->forceDelete();
        return response()->json([
            'alert' => 'success',
            'message' => 'Banner terhapus',
        ]);
    }
}

app/Http/Controllers/Office/ContactController.php
<?php

namespace App\Http\Controllers\Office;

use App\Http\Controllers\Controller;
use App\Models\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keywords = $request->keywords;
            $collection = Contact::where('email','like','%'.$keywords.'%')
            ->paginate(10);
            return view('page.office.contact.list', compact('collection'));
        }
        return view('page.office.contact.main');
    }
    public function create()
    {
        //
    }
    public function store(Request $request)
    {
        //
    }
    public function show(Contact $contact)
    {
        //
    }
    public function edit(Contact $contact)
    {
        //
    }
    public function update(Request $request, Contact $contact)
    {
        //
    }
    public function destroy(Contact $contact)
    {
        //
    }
}

app/Http/Controllers/Office/DashboardController.php
<?php

namespace App\Http\Controllers\Office;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Order;
use App\Models\User;
use App\Models\Vehicle;

class DashboardController extends Controller
{
    public function index()
    {
        $vehicle = Vehicle::get()->count();
        $order = Order::get()->count();
        $member = User::where("email_verified_at","!=",null)->count();
        return view('page.office.dashboard.main',compact('vehicle', 'order', 'member'));
    }
}

app/Http/Controllers/Office/EmployeeController.php
<?php

namespace App\Http\Controllers\Office;

use App\Http\Controllers\Controller;
use App\Models\Employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;

class EmployeeController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keywords = $request->keywords;
            $collection = Employee::where('name','like','%'.$keywords.'%')->paginate(10);
            return view('page.office.employee.list', compact('collection'));
        }
        return view('page.office.employee.main');
    }
    public function create()
    {
        return view('page.office.employee.input', ['employee' => new Employee]);
    }
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required|email|max:255',
            'password' => 'required|min:8',
            'name' => 'required',
        ]);

        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('email')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('email'),
                ]);
            }else if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name'),
                ]);
            }else{
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('password'),
                ]);
            }
        }
        $employee= new Employee;
        $employee->name = Str::title($request->name);
        $employee->email = $request->email;
        $employee->email_verified_at = date('Y-m-d H:i:s');
        $employee->created_at = date('Y-m-d H:i:s');
        $employee->updated_at = date('Y-m-d H:i:s');
        $employee->password = Hash::make($request->password);
        $employee->save();
        return response()->json([
            'alert' => 'success',
            'message' => 'Employee '. $request->name . ' tersimpan',
        ]);
    }
    public function show(Employee $employee)
    {
        //
    }
    public function edit(Employee $employee)
    {
        //
    }
    public function update(Request $request, Employee $employee)
    {
        //
    }
    public function destroy(Employee $employee)
    {
        $employee->forceDelete();
        return response()->json([
            'alert' => 'success',
            'message' => 'Banner terhapus',
        ]);
    }
}

app/Http/Controllers/Office/MemberController.php
<?php

namespace App\Http\Controllers\Office;

use App\Http\Controllers\Controller;
use App\Models\User;     
use App\Models\Category;     
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Validator;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $keywords = $request->keywords;
            $collection = User::where('name','like','%'.$keywords.'%')->where('role','2')
            ->paginate(10);
            return view('page.office.member.list', compact('collection'));
        }
        return view('page.office.member.main');
    }
    public function create()
    {
       //
    }
    public function store(Request $request)
    {
       //
    }
    public function show(User $member)
    {
        //
    }
    public function edit(User $member)
    {
        //
    }
    public function update(Request $request, User $member)
    {
       //
    }
    public function destroy(User $member)
    {
       //
    }
    public function verif(User $member){
        $member->email_verified_at =  date('Y-m-d H:i:s');
        $member->update();
        return response()->json([
            'alert' => 'success',
            'message' => 'User '. $member->name . ' terverifikasi',
        ]);
    }
}

app/View/Components/OfficeLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class OfficeLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('theme.office.main');
    }
}

resources/views/page/office/vehicleModel/input.blade.php
<div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">
    <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <div class="d-flex align-items-center flex-wrap mr-2">
            <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Vehicle-Model</h5>
            <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
            <span class="text-muted font-weight-bold mr-4">
                @if ($vehicleModel->id)
                    Update
                @else
                    Add
                @endif
                Data
            </span>
            <a href="javascript:;" onclick="load_list(1);" class="btn btn-light-warning font-weight-bolder btn-sm">Back</a>
        </div>
        <div class="d-flex align-items-center">
            
        </div>
    </div>
</div>
<div class="d-flex flex-column-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-xxl-12">
                <div class="card">
                    <form class="form" id="form_input">
                        <div class="card-body">
                            <div class="form-group row">
                                <div class="col-lg-6">
                                    <label>Name:</label>
                                    <input type="text" value="{{$vehicleModel->name}}" class="form-control" name="name" placeholder="Enter Name"/>
                                    <span class="form-text text-muted">Please enter name</span>
                                </div>
                                <div class="col-lg-6">
                                    <label>Name:</label>
                                    <select data-control="select2" data-placeholder="Pilih Vehicle-Model" id="brand_id" name="brand_id" class="form-control">
                                        <option SELECTED DISABLED>Pilih Vehicle-Model</option>
                                        @foreach ($brand as $item)
                                            <option value="{{$item->id}}"{{$vehicleModel->brand_id==$item->id ? 'selected' : ''}}>{{$item->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="row">
                                <div class="col-lg-6">
                                    @if ($vehicleModel->id)
                                    <button type="button" id="tombol_simpan" onclick="handle_save('#tombol_simpan','#form_input','{{route('office.vehicleModel.update',$vehicleModel->id)}}','PATCH');" class="btn btn-primary mr-2">Save</button>
                                    @else
                                    <button type="button" id="tombol_simpan" onclick="handle_save('#tombol_simpan','#form_input','{{route('office.vehicleModel.store')}}','POST');" class="btn btn-primary mr-2">Save</button>
                                    @endif
                                    <button onclick="load_list(1);" class="btn btn-secondary">Cancel</button>
                                </div>
                                @if ($vehicleModel->id)
                                <div class="col-lg-6 text-lg-right">
                                    <button type="reset" class="btn btn-danger">Delete</button>
                                </div>
                                @endif
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

</script>

resources/views/page/office/vehicleModel/list.blade.php
<table class="table">
    <thead>
        <tr>
            <th>No</th>
            <th>Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @php
        $no = 1;
        @endphp
        @foreach ($collection as $item)
        <tr>
            <td>{{$no++}}</td>
            <td>{{$item->name}}</td>
            <td>
                <a href="javascript:;" onclick="load_input('{{route('office.vehicleModel.edit',$item->id)}}');" class="btn btn-icon btn-outline-warning btn-circle mr-2">
                    <i class="flaticon-file"></i>
                </a>
                <a href="javascript:;" onclick="handle_confirm('Delete Confirmation','Yes','Cancel','DELETE','{{route('office.vehicleModel.destroy',$item->id)}}');" class="btn btn-icon btn-outline-danger btn-circle mr-2">
                    <i class="flaticon-file"></i>
                </a>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
{{$collection->links('theme.office.pagination')}}

resources/views/page/office/vehicleModel/main.blade.php
<x-office-layout title="Vehicle-model">
    <div id="content_list">
        <div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">
            <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
                <div class="d-flex align-items-center flex-wrap mr-2">
                    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Vehicle-Model</h5>
                    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
                    <span class="text-muted font-weight-bold mr-4">List Data</span>
                    <a href="javascript:;" onclick="load_input('{{route('office.vehicleModel.create')}}');" class="btn btn-light-warning font-weight-bolder btn-sm">Add New</a>
                </div>
                <div class="d-flex align-items-center">
                    <form id="content_filter">
                        <input class="form-control" onkeyup="load_list(1);" name="keywords" placeholder="Search here...">
                    </form>
                </div>
            </div>
        </div>
        <div class="d-flex flex-column-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-xxl-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <div id="list_result"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="content_input"></div>
    @section('custom_js')
        <script type="text/javascript">
            load_list(1);
        </script>
    @endsection
</x-office-layout>