app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;
    protected $table = 'order';
    public $timestamps = false;
    protected $casts = [
        'booking_at' => 'date',
        'take_at' => 'datetime',
        'return_at' => 'datetime',
        'created_at' => 'datetime',
    ];
    public function getImageAttribute()
    {
        return asset('storage/' . $this->photo);
    }
    public function vehicle(){
        return $this->belongsTo(Vehicle::class,'vehicle_id','id');
    }
    public function user(){
        return $this->belongsTo(User::class,'user_id','id');
    }
}

app/Http/Controllers/Web/ProfileController.php
<?php

namespace App\Http\Controllers\Web;

use App\Models\User;
use App\Models\Vehicle;
use App\Models\Order;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Rules\MatchOldPassword;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class ProfileController extends Controller
{
    public function index(Request $request)
    {   
        if (Auth::guard('member')->user()->role == 1){
            $order = Order::where('user_id', Auth::guard('member')->user()->id)->get();
        }else{
            $order = Order::get();
        }
        $mobil = Vehicle::where('user_id', Auth::guard('member')->user()->id)->get();
        $profile = User::where('id',Auth::guard('member')->user()->id)->first();
        if ($request->ajax()) {
            $keywords = $request->keywords;
            $collection = Order::where('user_id',$profile->id)
            ->paginate(10);
            return view('page.web.profile.list', compact('collection'));
        }
        return view('page.web.profile.main',compact('profile','mobil','order'));
    }
    public function edit()
    {
        return view('page.web.profile.input');
    }
    public function update(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required|email|max:255',
            'name' => 'required',
            'nik'=>'required',
            'address'=>'required',
            'ktp'=>'required',
        ]);

        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('email')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('email'),
                ]);
            }else if ($errors->has('name')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('name'),
                ]);
            }else if ($errors->has('nik')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('nik'),
                ]);
            }else if ($errors->has('address')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('address'),
                ]);
            }else{
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('ktp'),
                ]);
            }
        }
        $user = User::where('id', Auth::guard('member')->user()->id)->first();
        if(request()->file('ktp')){
            Storage::delete($user->ktp);
            $photo = request()->file('ktp')->store("profile");
            $user->ktp = $photo;
        }
        $user->name = Str::title($request->name);
        $user->email = $request->email;
        $user->nik = $request->nik;
        $user->address = $request->address;
        $user->update();
        return response()->json([
            'alert' => 'success',
            'message' => 'Profile '. $request->name . ' terupdate',
        ]);
    }
    public function update_password(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'current_password' => ['required', new MatchOldPassword],
            'new_password' => ['required'],
            'new_confirm_password' => ['same:new_password'],
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('current_password')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('current_password'),
                ]);
            } elseif ($errors->has('new_password')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('new_password'),
                ]);
            } elseif ($errors->has('new_confirm_password')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('new_confirm_password'),
                ]);
            }
        }
        User::find(auth()->user()->id)->update(['password'=> Hash::make($request->new_password)]);
        $profile = User::where('id',Auth::guard('member')->user()->id)->first();
        // Mail::to($profile->email)->send(new PasswordChangedMail($profile));
        $profile = Auth::guard('member')->user();
        Auth::logout($profile);
        return response()->json([
            'alert' => 'success',
            'message' => 'Password changed successfully',
        ]);
    }
    public function update_bank(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'no_rek' => 'required',
            'nama_rek' => 'required',
            'bank' => 'required',
        ]);
        if ($validator->fails()) {
            $errors = $validator->errors();
            if ($errors->has('no_rek')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('no_rek'),
                ]);
            } elseif ($errors->has('nama_rek')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('nama_rek'),
                ]);
            } elseif ($errors->has('bank')) {
                return response()->json([
                    'alert' => 'error',
                    'message' => $errors->first('bank'),
                ]);
            }
        }
        $user = User::where('id',Auth::guard('member')->user()->id)->first();
        $user->no_rek = $request->no_rek;
        $user->nama_rek = $request->nama_rek;
        $user->bank = $request->bank;
        $user->update();
        return response()->json([
            'alert' => 'success',
            'message' => 'Bank account successfully',
        ]);
    }
}

app/View/Components/WebLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class WebLayout extends Component
{
    public $title;
    public function __construct($title)
    {
        $this->title = $title;
    }
    public function render()
    {
        return view('theme.web.main');
    }
}

resources/views/page/web/profile/input.blade.php
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">
            <div class="row clearfix">
                <div class="col-lg-12">
                    <a href="javascript:;" onclick="load_list(1);" class="button button-rounded button-small m-0 ms-2 float-end">Kembali</a>
                    <div class="heading-block border-0">
                        <h3>{{Auth::guard('member')->user()->name}}</h3>
                    </div>
                    <div class="clear"></div>
                    <h5 class="me-3 mt-3">Informasi Dasar</h5>
                    <div class="card">
                        <div class="card-body">
                            <form id="form_basic_info">
                                <div class="form-group row">
                                    <div class="col-4">
                                        <label>Nama</label>
                                        <input type="text" name="name" class="form-control" placeholder="Full name" value="{{Auth::guard('member')->user()->name}}" />
                                    </div>
                                    <div class="col-4">
                                        <label>Email</label>
                                        <input type="email" name="email" class="form-control" value="{{Auth::guard('member')->user()->email}}" />
                                    </div>
                                    <div class="col-3">
                                        <label>NIK</label>
                                        <input type="tel" id="nik" name="nik" minlength="16" maxlength="16" class="form-control" value="{{Auth::guard('member')->user()->nik}}" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-6">
                                        <label>Alamat</label>
                                        <textarea name="address" class="form-control"></textarea>
                                    </div>
                                    <div class="col-6">
                                        <label>Foto KTP</label>
                                        <input type="file" class="form-control" name="ktp">
                                    </div>
                                </div>
                                <button id="tombol_simpan_basic" onclick="handle_upload('#tombol_simpan_basic','#form_basic_info','{{route('web.profile.update')}}','POST')" class="button button-rounded button-small m-0 ms-2 float-end">Simpan Perubahan</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12 mt-3">
                    <h5 class="me-3 mt-3">Keamanan Akun</h5>
                    <div class="card">
                        <div class="card-body">
                            <form id="form_password">
                                <div class="form-group row">
                                    <div class="col-4">
                                        <label>Kata Sandi Saat ini</label>
                                        <input type="password" class="form-control" name="current_password" id="current_password" />
                                    </div>
                                    <div class="col-4">
                                        <label>Kata Sandi</label>
                                        <input type="password" class="form-control" name="new_password" id="new_password" />
                                    </div>
                                    <div class="col-4">
                                        <label>Konfirmasi Kata Sandi</label>
                                        <input type="password" class="form-control" name="new_confirm_password" id="new_confirm_password" />
                                    </div>
                                </div>
                                <button id="tombol_simpan_password" onclick="handle_save('#tombol_simpan_password','#form_password','{{route('web.profile.cpassword')}}','POST')" class="button button-rounded button-small m-0 ms-2 float-end">Ubah Kata Sandi</button>
                                {{-- <button id="tombol_save" onclick="handle_save('#tombol_save','#password_form','{{route('office.profile.cpassword')}}','POST')" class="btn btn-primary" >Save Changes</button> --}}
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12 mt-3">
                    <h5 class="me-3 mt-3">Keuangan</h5>
                    <div class="card">
                        <div class="card-body">
                            <form id="form_keuangan">
                                <div class="form-group row">
                                    <div class="col-4">
                                        <label>No Rekening</label>
                                        <input type="text" class="form-control" name="no_rek" id="no_rek" />
                                    </div>
                                    <div class="col-4">
                                        <label>Nama Pemilik Rekening</label>
                                        <input type="text" class="form-control" name="nama_rek" id="nama_rek" />
                                    </div>
                                    <div class="col-4">
                                        <label>Nama Bank</label>
                                       <select  class="form-control" name="bank" id="bank">
                                           <option value="bca">BCA</option>
                                           <option value="mandiri">MANDIRI</option>
                                           <option value="bni">BNI</option>
                                           <option value="bri">BRI</option>
                                       </select>
                                    </div>
                                </div>
                                <button id="tombol_simpan_bank" onclick="handle_save('#tombol_simpan_bank','#form_keuangan','{{route('web.profile.cbank')}}','POST')" class="button button-rounded button-small m-0 ms-2 float-end">Ubah Data Bank</button>
                                {{-- <button id="tombol_save" onclick="handle_save('#tombol_save','#password_form','{{route('office.profile.cpassword')}}','POST')" class="btn btn-primary" >Save Changes</button> --}}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    number_only('no_rek');
</script>

resources/views/page/web/profile/input_vehicle.blade.php
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">
            <div class="row clearfix">
                <div class="col-lg-12">
                    <a href="javascript:;" onclick="load_list(1);" class="button button-rounded button-small m-0 ms-2 float-end">Kembali</a>
                    <div class="heading-block border-0">
                        <h3>{{Auth::guard('member')->user()->name}}</h3>
                    </div>
                    <div class="clear"></div>
                    <h5 class="me-3 mt-3">Tambah Kendaraan</h5>
                    <div class="card">
                        <div class="card-body">
                            <form id="form_basic_info">
                                <div class="form-group row">
                                    <div class="col-3">
                                        <label>Nama</label>
                                        <input type="text" name="name" class="form-control" placeholder="Full name" value="{{Auth::guard('member')->user()->name}}" />
                                    </div>
                                    <div class="col-3">
                                        <label>Brand:</label>
                                        <select data-control="select2" data-placeholder="Pilih Brand" id="brand_id" name="brand_id" class="form-control">
                                            <option SELECTED DISABLED>Pilih Brand</option>
                                            @foreach ($brand as $item)
                                                <option value="{{$item->id}}"{{$vehicle->brand_id==$item->id ? 'selected' : ''}}>{{$item->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-3">
                                        <label>Category:</label>
                                        <select data-control="select2" data-placeholder="Pilih Category" id="category_id" name="category_id" class="form-control">
                                            <option SELECTED DISABLED>Pilih Category</option>
                                            @foreach ($category as $item)
                                                <option value="{{$item->id}}"{{$vehicle->category_id==$item->id ? 'selected' : ''}}>{{$item->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-3">
                                        <label>Vehicle Model:</label>
                                        <select data-control="select2" data-placeholder="Pilih Category" id="vehicle_model_id" name="vehicle_model_id" class="form-control">
                                            <option SELECTED DISABLED>Pilih Vehicle-model</option>
                                            @foreach ($vehicleModel as $item)
                                                <option value="{{$item->id}}"{{$vehicle->vehicle_model_id==$item->id ? 'selected' : ''}}>{{$item->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-6">
                                        <label>Deskripsi</label>
                                        <textarea name="desc" class="form-control"></textarea>
                                    </div>
                                    <div class="col-6">
                                        <label>Foto</label>
                                        <input type="file" class="form-control" name="photo">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-12">
                                        <label>Harga:</label>
                                        <input type="text" value="{{number_format($vehicle->price)}}" id="price" class="form-control" name="price" placeholder="Masukkan Harga.."/>
                                    </div>
                                </div> 
                                @if ($vehicle->id)
                                <button id="tombol_simpan_basic" onclick="handle_upload('#tombol_simpan_basic','#form_basic_info','{{route('web.vehicle.update',$item->id)}}','PATCH')" class="button button-rounded button-small m-0 ms-2 float-end">Simpan Perubahan</button>
                                @else
                                <button id="tombol_simpan_basic" onclick="handle_upload('#tombol_simpan_basic','#form_basic_info','{{route('web.vehicle.store')}}','POST')" class="button button-rounded button-small m-0 ms-2 float-end">Simpan Perubahan</button>
                                @endif
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    number_only('price');
    ribuan('price');
</script>

resources/views/page/web/profile/main.blade.php
<x-web-layout title="Profil Saya">
    <div id="content_list">
        <section id="content">
            <div class="content-wrap">
                <div class="container clearfix">
                    <div class="row clearfix">
                        <div class="col-md-9">
                            <a href="javascript:;" onclick="load_input('{{route('web.profile.edit')}}');" class="button button-rounded button-small m-0 ms-2 float-end">Ubah Profil</a>
                            <img src="{{$profile->image}}" class="alignleft img-circle img-thumbnail my-0" alt="Avatar" style="max-width: 84px;">
                            <div class="heading-block border-0">
                                <h3>{{Auth::guard('member')->user()->name}}</h3>
                                <span>{{Auth::guard('member')->user()->bio}}</span>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="col-md-3">
                            <div class="list-group">
                                <a href="{{route('web.profile.index')}}" class="{{request()->is('profile/*') ? 'active' : ''}} list-group-item list-group-item-action d-flex justify-content-between"><div>Profil</div><i class="icon-user"></i></a>
                                <a href="{{route('web.auth.logout')}}" class="list-group-item list-group-item-action d-flex justify-content-between"><div>Keluar</div><i class="icon-line2-logout"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div id="content_input"></div>
    @section('custom_js')
        <script>
            // load_list(1);
        </script>
    @endsection
</x-web-layout>